### ISSUE TITLE
Support hspec-discover?

### ISSUE THREAD

**Issue by FranklinChen** [kowainik/.github#9]
I'm just starting out with GitHub Actions and copied your config but seem to be having a problem with hspec-discover not being found: https://github.com/FranklinChen/spreadsheet-haskell/runs/1439645166?check_suite_focus=true

```
ghc: could not execute: hspec-discover
```

Could you add support for this?

**Comment by chshersh** [comment]
Hi @FranklinChen! I'm afraid, this is not a problem of the GItHub actions config. All Haskell dependencies (including `hspec-discover`) should be handled on the project level, not by the CI configuration. I see, that you don't have `hspec-discover` currently specified in your `.cabal` file, that's why both GHC and Cabal don't know about it.

**Comment by FranklinChen** [comment]
Thanks, I didn't know I was missing something. I've added `build-tool-depends` as needed to my `package.yaml` (and therefore the generated Cabal file also).
